CREATE TABLE IF NOT EXISTS FACT_TRANSACTIONS_STREAMING (
    TRANSACTION_ID      STRING      PRIMARY KEY,
    CARD_ID             STRING,
    CUSTOMER_ID         STRING,
    MERCHANT_ID         STRING,
    AMOUNT              NUMBER(18,2),
    CURRENCY            STRING,
    COUNTRY             STRING,
    CHANNEL             STRING,
    EVENT_TIME_UTC      TIMESTAMP_TZ,
    TXN_DATE            DATE,
    TXN_HOUR            NUMBER(2,0),
    IS_HIGH_VALUE       BOOLEAN,
    IS_INTERNATIONAL    BOOLEAN,
    INGESTED_AT         TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS FACT_CARD_ACTIVITY_15M (
    CARD_ID                 STRING,
    WINDOW_START            TIMESTAMP_TZ,
    WINDOW_END              TIMESTAMP_TZ,
    TXN_COUNT               NUMBER,
    TOTAL_AMOUNT            NUMBER(18,2),
    HIGH_VALUE_TXN_COUNT    NUMBER
);

CREATE TABLE IF NOT EXISTS DIM_CARD (
    CARD_ID         STRING PRIMARY KEY,
    CUSTOMER_ID     STRING,
    HOME_COUNTRY    STRING,
    RISK_TIER       STRING
);
