-- ============================================================
-- Snowflake RBAC — Merchant Reconciliation Platform
--
-- Role hierarchy:
--   SYSADMIN
--   └── RECONCILIATION_ENGINEER   (write + DDL)
--       └── RECONCILIATION_ANALYST (read-only: views + select)
--
-- Principle of least privilege:
--   - Analysts cannot see raw card_id / customer_id (column masking)
--   - Engineers cannot modify RBAC (that stays with SECURITYADMIN)
--   - Service accounts use dedicated roles, not personal accounts
-- ============================================================

USE ROLE SECURITYADMIN;


-- ── Roles ─────────────────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS RECONCILIATION_ENGINEER
    COMMENT = 'Full read/write access to RECONCILIATION_DB.GOLD — pipeline service accounts';

CREATE ROLE IF NOT EXISTS RECONCILIATION_ANALYST
    COMMENT = 'Read-only access to Gold views — business analysts and audit users';

-- Role hierarchy: analyst is a subset of engineer
GRANT ROLE RECONCILIATION_ANALYST TO ROLE RECONCILIATION_ENGINEER;

-- Grant to SYSADMIN so admins can always access for ops
GRANT ROLE RECONCILIATION_ENGINEER TO ROLE SYSADMIN;


-- ── Warehouse grants ───────────────────────────────────────────────────────────

GRANT USAGE ON WAREHOUSE RECONCILIATION_WH TO ROLE RECONCILIATION_ENGINEER;
GRANT USAGE ON WAREHOUSE RECONCILIATION_WH TO ROLE RECONCILIATION_ANALYST;
GRANT OPERATE ON WAREHOUSE RECONCILIATION_WH TO ROLE RECONCILIATION_ENGINEER;


-- ── Database / schema grants ───────────────────────────────────────────────────

GRANT USAGE ON DATABASE RECONCILIATION_DB TO ROLE RECONCILIATION_ENGINEER;
GRANT USAGE ON DATABASE RECONCILIATION_DB TO ROLE RECONCILIATION_ANALYST;

GRANT USAGE ON SCHEMA RECONCILIATION_DB.GOLD TO ROLE RECONCILIATION_ENGINEER;
GRANT USAGE ON SCHEMA RECONCILIATION_DB.GOLD TO ROLE RECONCILIATION_ANALYST;

GRANT USAGE ON SCHEMA RECONCILIATION_DB.STAGING TO ROLE RECONCILIATION_ENGINEER;


-- ── Table grants — ENGINEER (full CRUD + DDL) ─────────────────────────────────

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA RECONCILIATION_DB.GOLD
    TO ROLE RECONCILIATION_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA RECONCILIATION_DB.GOLD
    TO ROLE RECONCILIATION_ENGINEER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA RECONCILIATION_DB.STAGING
    TO ROLE RECONCILIATION_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA RECONCILIATION_DB.STAGING
    TO ROLE RECONCILIATION_ENGINEER;


-- ── Table grants — ANALYST (read-only) ────────────────────────────────────────

-- Views only — analysts should not query raw tables directly
GRANT SELECT ON ALL VIEWS IN SCHEMA RECONCILIATION_DB.GOLD
    TO ROLE RECONCILIATION_ANALYST;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA RECONCILIATION_DB.GOLD
    TO ROLE RECONCILIATION_ANALYST;

-- Allow direct table access for ANOMALY_LOG (no PII)
GRANT SELECT ON TABLE RECONCILIATION_DB.GOLD.ANOMALY_LOG
    TO ROLE RECONCILIATION_ANALYST;

GRANT SELECT ON TABLE RECONCILIATION_DB.GOLD.DIM_MERCHANT
    TO ROLE RECONCILIATION_ANALYST;


-- ── Column-level security — mask PII for ANALYST role ─────────────────────────

USE ROLE SYSADMIN;

-- Masking policy for CARD_ID: analysts see only last 4 chars
CREATE MASKING POLICY IF NOT EXISTS RECONCILIATION_DB.GOLD.MASK_CARD_ID
AS (CARD_ID VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('RECONCILIATION_ENGINEER', 'SYSADMIN', 'ACCOUNTADMIN')
        THEN CARD_ID
        ELSE CONCAT('****-****-****-', RIGHT(CARD_ID, 4))
    END
COMMENT = 'Mask CARD_ID for non-engineer roles';

ALTER TABLE RECONCILIATION_DB.GOLD.RECONCILIATION_RESULTS
    MODIFY COLUMN CARD_ID
    SET MASKING POLICY RECONCILIATION_DB.GOLD.MASK_CARD_ID;

-- Masking policy for CUSTOMER_ID
CREATE MASKING POLICY IF NOT EXISTS RECONCILIATION_DB.GOLD.MASK_CUSTOMER_ID
AS (CUSTOMER_ID VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('RECONCILIATION_ENGINEER', 'SYSADMIN', 'ACCOUNTADMIN')
        THEN CUSTOMER_ID
        ELSE SHA2(CUSTOMER_ID, 256)  -- pseudonymise with SHA-256 hash
    END
COMMENT = 'Pseudonymise CUSTOMER_ID for non-engineer roles';

ALTER TABLE RECONCILIATION_DB.GOLD.RECONCILIATION_RESULTS
    MODIFY COLUMN CUSTOMER_ID
    SET MASKING POLICY RECONCILIATION_DB.GOLD.MASK_CUSTOMER_ID;


-- ── Service accounts ───────────────────────────────────────────────────────────

-- Pipeline service account (Databricks job)
CREATE USER IF NOT EXISTS SVC_RECONCILIATION_PIPELINE
    PASSWORD = 'CHANGE_ME_ON_FIRST_LOGIN'       -- rotate immediately; use key-pair auth in prod
    DEFAULT_ROLE = RECONCILIATION_ENGINEER
    DEFAULT_WAREHOUSE = RECONCILIATION_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Databricks pipeline service account — use RSA key-pair auth';

GRANT ROLE RECONCILIATION_ENGINEER TO USER SVC_RECONCILIATION_PIPELINE;

-- Analyst team group (human users granted by SECURITYADMIN separately)
-- GRANT ROLE RECONCILIATION_ANALYST TO USER <analyst_username>;


-- ── Row-level security — optional (merchant isolation) ───────────────────────

-- Uncomment to restrict analysts to their assigned merchant IDs.
-- This requires a mapping table: GOLD.ANALYST_MERCHANT_MAP (ANALYST_EMAIL, MERCHANT_ID)

-- CREATE ROW ACCESS POLICY IF NOT EXISTS RECONCILIATION_DB.GOLD.RAP_MERCHANT_ISOLATION
-- AS (MERCHANT_ID VARCHAR) RETURNS BOOLEAN ->
--     CURRENT_ROLE() IN ('RECONCILIATION_ENGINEER', 'SYSADMIN')
--     OR EXISTS (
--         SELECT 1 FROM RECONCILIATION_DB.GOLD.ANALYST_MERCHANT_MAP
--         WHERE ANALYST_EMAIL = CURRENT_USER()
--         AND MERCHANT_ID = MERCHANT_ID
--     );
--
-- ALTER TABLE RECONCILIATION_DB.GOLD.RECONCILIATION_RESULTS
--     ADD ROW ACCESS POLICY RECONCILIATION_DB.GOLD.RAP_MERCHANT_ISOLATION
--     ON (MERCHANT_ID);
